package conversion_infixtopostfix;

import java.io.OutputStream;
import java.io.PrintStream;
/**
 *
 * @author Natthakit
 */
public class MainGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGUI.class.getName());

    public MainGUI() {
        initComponents();
        setTitle("Infix to Postfix Converter");
    
        // Redirect System.out → JTextArea
        OutputStream out = new OutputStream() {
            @Override
            public void write(int b) {
                jTextArea1.append(String.valueOf((char) b));
            }
        };
        System.setOut(new PrintStream(out, true));
    
        jTextArea1.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 13));    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInput = new javax.swing.JTextField();
        txtOutput = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        convert = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(620, 480));
        setType(java.awt.Window.Type.POPUP);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        txtOutput.setViewportView(jTextArea1);

        convert.setBackground(new java.awt.Color(153, 255, 153));
        convert.setText("convert");
        convert.addActionListener(this::convertActionPerformed);

        clear.setBackground(new java.awt.Color(255, 102, 102));
        clear.setText("clear");
        clear.addActionListener(this::clearActionPerformed);

        jLabel1.setText("Enter an infix expression");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(convert)
                        .addGap(18, 18, 18)
                        .addComponent(clear))
                    .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear)
                    .addComponent(convert))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        txtInput.setText("");
        jTextArea1.setText("");
        txtInput.requestFocus();
    }//GEN-LAST:event_clearActionPerformed

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
        String infix = txtInput.getText().trim();
        jTextArea1.setText("");
        try {
            InfixToPostfix conversion = new InfixToPostfix(infix);
            conversion.convert();
            System.out.println("-".repeat(60));
            System.out.println("Postfix: " + conversion.getPostfix());
        } 
        catch (IllegalArgumentException e) { System.out.println(e.getMessage()); }
        catch (Exception e) { System.out.println("Something went wrong."); }
    }//GEN-LAST:event_convertActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new MainGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton convert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtInput;
    private javax.swing.JScrollPane txtOutput;
    // End of variables declaration//GEN-END:variables
}
